chapter {* Generated by Lem from /home/sami/base/verification/evm.lem. *}

theory "EvmAuxiliary" 

imports 
 	 Main "~~/src/HOL/Library/Code_Target_Numeral"
	 "Lem_pervasives" 
	 "Lem_word" 
	 "Word256" 
	 "Word160" 
	 "Word8" 
	 "Evm" 

begin 


(****************************************************)
(*                                                  *)
(* Termination Proofs                               *)
(*                                                  *)
(****************************************************)

termination drop_bytes by lexicographic_order

termination program_size by lexicographic_order

termination program_code by lexicographic_order

termination store_byte_list_in_program by lexicographic_order

termination program_content_of_lst by lexicographic_order

termination program_annotation_of_lst by lexicographic_order

termination venv_pop_stack by lexicographic_order

termination cut_memory by lexicographic_order

termination store_byte_list_memory by lexicographic_order

termination word_rsplit_aux by lexicographic_order

termination program_sem by lexicographic_order

termination put_return_values by lexicographic_order


(****************************************************)
(*                                                  *)
(* Lemmata                                          *)
(*                                                  *)
(****************************************************)

lemma uint_to_address_def_lemma:
" ((\<forall> w. word160FromNat (unat w) = Word.ucast w)) "
(* Theorem: uint_to_address_def_lemma*)(* try *) by auto

lemma address_to_uint_def_lemma:
" ((\<forall> w. word256FromNat (word160ToNat w) = Word.ucast w)) "
(* Theorem: address_to_uint_def_lemma*)(* try *) by auto

lemma uint_to_byte_def_lemma:
" ((\<forall> w. word8FromNat (unat w) = Word.ucast w)) "
(* Theorem: uint_to_byte_def_lemma*)(* try *) by auto

lemma byte_to_uint_def_lemma:
" ((\<forall> w. word256FromNat (word8ToNat w) = Word.ucast w)) "
(* Theorem: byte_to_uint_def_lemma*)(* try *) by auto

lemma word_rsplit_def_lemma:
" ((\<forall> w.
   word_rsplit_aux (boolListFromWord256 w) (( 32 :: nat)) = word_rsplit w)) "
(* Theorem: word_rsplit_def_lemma*)(* try *) by auto



end
