chapter {* Generated by Lem from rlp.lem. *}

theory "RlpAuxiliary" 

imports 
 	 Main "~~/src/HOL/Library/Code_Target_Numeral"
	 "Lem_pervasives" 
	 "Lem_word" 
	 "Word256" 
	 "Word160" 
	 "Word8" 
	 "Rlp" 

begin 


(****************************************************)
(*                                                  *)
(* Termination Proofs                               *)
(*                                                  *)
(****************************************************)

termination BE_rev by lexicographic_order

termination BD_rev by lexicographic_order

termination RLP by lexicographic_order

termination decode by lexicographic_order



end
