chapter {* Generated by Lem from word160.lem. *}

theory "Word160Auxiliary" 

imports 
 	 Main "~~/src/HOL/Library/Code_Target_Numeral"
	 "Lem_pervasives" 
	 "Lem_word" 
	 "Word160" 

begin 


(****************************************************)
(*                                                  *)
(* Lemmata                                          *)
(*                                                  *)
(****************************************************)

lemma bs_to_w160_def_lemma:
" ((\<forall> seq.
   (case  resizeBitSeq (Some (( 160 :: nat))) seq of
         BitSeq _ s b => W160 s b
   ) = (\<lambda> w .  word_of_int (integerFromBitSeq w)) seq)) "
(* Theorem: bs_to_w160_def_lemma*)(* try *) by auto

lemma w160_to_bs_def_lemma:
" ((\<forall> s. \<forall> b.
   BitSeq (Some (( 160 :: nat))) s b =
     (\<lambda> w .  bitSeqFromInteger (Some 160) ( (sint w))) (W160 s b))) "
(* Theorem: w160_to_bs_def_lemma*)(* try *) by auto

lemma word160ToNat_def_lemma:
" ((\<forall> w.
   nat
     (abs
        (
           (integerFromBitSeq
              ((\<lambda> w .  bitSeqFromInteger (Some 160) ( (sint w))) w))))
     = unat w)) "
(* Theorem: word160ToNat_def_lemma*)(* try *) by auto

lemma word160ToInt_def_lemma:
" ((\<forall> w.
   
     (integerFromBitSeq
        ((\<lambda> w .  bitSeqFromInteger (Some 160) ( (sint w))) w)) =
     sint w)) "
(* Theorem: word160ToInt_def_lemma*)(* try *) by auto

lemma word160FromInteger_def_lemma:
" ((\<forall> i.
   (\<lambda> w .  word_of_int (integerFromBitSeq w))
     (bitSeqFromInteger (Some (( 160 :: nat))) i) =
     (\<lambda> i .  word_of_int ( i)) i)) "
(* Theorem: word160FromInteger_def_lemma*)(* try *) by auto

lemma word160FromInt_def_lemma:
" ((\<forall> i.
   (\<lambda> w .  word_of_int (integerFromBitSeq w))
     (bitSeqFromInteger (Some (( 160 :: nat))) ( i)) = word_of_int i)) "
(* Theorem: word160FromInt_def_lemma*)(* try *) by auto

lemma word160FromBoollist_def_lemma:
" ((\<forall> lst.
   (case  bitSeqFromBoolList lst of
         None => (\<lambda> w .  word_of_int (integerFromBitSeq w))
                   (bitSeqFromInteger None (( 0 :: int)))
     | Some a => (\<lambda> w .  word_of_int (integerFromBitSeq w)) a
   ) = of_bl lst)) "
(* Theorem: word160FromBoollist_def_lemma*)(* try *) by auto

lemma boolListFromWord160_def_lemma:
" ((\<forall> w.
   boolListFrombitSeq (( 160 :: nat))
     ((\<lambda> w .  bitSeqFromInteger (Some 160) ( (sint w))) w) = 
   of_bl w)) "
(* Theorem: boolListFromWord160_def_lemma*)(* try *) by auto

lemma word160FromNumeral_def_lemma:
" ((\<forall> w.
   (\<lambda> w .  word_of_int (integerFromBitSeq w))
     (bitSeqFromInteger None (( w :: int))) = ((word_of_int w) :: 160 word))) "
(* Theorem: word160FromNumeral_def_lemma*)(* try *) by auto

lemma w160Less_def_lemma:
" ((\<forall> bs1. \<forall> bs2.
   word160BinTest bitSeqLess bs1 bs2 = word_sless bs1 bs2)) "
(* Theorem: w160Less_def_lemma*)(* try *) by auto

lemma w160LessEqual_def_lemma:
" ((\<forall> bs1. \<forall> bs2.
   word160BinTest bitSeqLessEqual bs1 bs2 = word_sle bs1 bs2)) "
(* Theorem: w160LessEqual_def_lemma*)(* try *) by auto

lemma w160Greater_def_lemma:
" ((\<forall> bs1. \<forall> bs2.
   word160BinTest bitSeqGreater bs1 bs2 = word_sless bs2 bs1)) "
(* Theorem: w160Greater_def_lemma*)(* try *) by auto

lemma w160GreaterEqual_def_lemma:
" ((\<forall> bs1. \<forall> bs2.
   word160BinTest bitSeqGreaterEqual bs1 bs2 = word_sle bs2 bs1)) "
(* Theorem: w160GreaterEqual_def_lemma*)(* try *) by auto

lemma w160Compare_def_lemma:
" ((\<forall> bs1. \<forall> bs2.
   word160BinTest bitSeqCompare bs1 bs2 =
     (genericCompare word_sless w160Eq bs1 bs2))) "
(* Theorem: w160Compare_def_lemma*)(* try *) by auto

lemma word160Negate_def_lemma:
" (( word160UnaryOp bitSeqNegate = (\<lambda> i. - i))) "
(* Theorem: word160Negate_def_lemma*)(* try *) by auto

lemma word160Succ_def_lemma:
" (( word160UnaryOp bitSeqSucc = (\<lambda> n. n + 1))) "
(* Theorem: word160Succ_def_lemma*)(* try *) by auto

lemma word160Pred_def_lemma:
" (( word160UnaryOp bitSeqPred = (\<lambda> n. n - 1))) "
(* Theorem: word160Pred_def_lemma*)(* try *) by auto

lemma word160Lnot_def_lemma:
" (( word160UnaryOp bitSeqNot = (\<lambda> w. (NOT w)))) "
(* Theorem: word160Lnot_def_lemma*)(* try *) by auto

lemma word160Add_def_lemma:
" (( word160BinOp bitSeqAdd = (op+))) "
(* Theorem: word160Add_def_lemma*)(* try *) by auto

lemma word160Minus_def_lemma:
" (( word160BinOp bitSeqMinus = (op-))) "
(* Theorem: word160Minus_def_lemma*)(* try *) by auto

lemma word160Mult_def_lemma:
" (( word160BinOp bitSeqMult = (op*))) "
(* Theorem: word160Mult_def_lemma*)(* try *) by auto

lemma word160IntegerDivision_def_lemma:
" (( word160BinOp bitSeqDiv = (op div))) "
(* Theorem: word160IntegerDivision_def_lemma*)(* try *) by auto

lemma word160Division_def_lemma:
" (( word160BinOp bitSeqDiv = (op div))) "
(* Theorem: word160Division_def_lemma*)(* try *) by auto

lemma word160Remainder_def_lemma:
" (( word160BinOp bitSeqMod = (op mod))) "
(* Theorem: word160Remainder_def_lemma*)(* try *) by auto

lemma word160Land_def_lemma:
" (( word160BinOp bitSeqAnd = (op AND))) "
(* Theorem: word160Land_def_lemma*)(* try *) by auto

lemma word160Lor_def_lemma:
" (( word160BinOp bitSeqOr = (op OR))) "
(* Theorem: word160Lor_def_lemma*)(* try *) by auto

lemma word160Lxor_def_lemma:
" (( word160BinOp bitSeqXor = (op XOR))) "
(* Theorem: word160Lxor_def_lemma*)(* try *) by auto

lemma word160Min_def_lemma:
" (( word160BinOp (bitSeqMin) = min)) "
(* Theorem: word160Min_def_lemma*)(* try *) by auto

lemma word160Max_def_lemma:
" (( word160BinOp (bitSeqMax) = max)) "
(* Theorem: word160Max_def_lemma*)(* try *) by auto

lemma word160Power_def_lemma:
" (( word160NatOp bitSeqPow = (op^))) "
(* Theorem: word160Power_def_lemma*)(* try *) by auto

lemma word160Asr_def_lemma:
" (( word160NatOp bitSeqArithmeticShiftRight = (op>>>))) "
(* Theorem: word160Asr_def_lemma*)(* try *) by auto

lemma word160Lsr_def_lemma:
" (( word160NatOp bitSeqLogicalShiftRight = (op>>))) "
(* Theorem: word160Lsr_def_lemma*)(* try *) by auto

lemma word160Lsl_def_lemma:
" (( word160NatOp bitSeqShiftLeft = (op<<))) "
(* Theorem: word160Lsl_def_lemma*)(* try *) by auto



end
