chapter {* Generated by Lem from word256.lem. *}

theory "Word256Auxiliary" 

imports 
 	 Main "~~/src/HOL/Library/Code_Target_Numeral"
	 "Lem_pervasives" 
	 "Lem_word" 
	 "Word256" 

begin 


(****************************************************)
(*                                                  *)
(* Lemmata                                          *)
(*                                                  *)
(****************************************************)

lemma bs_to_w256_def_lemma:
" ((\<forall> seq.
   (case  resizeBitSeq (Some (( 256 :: nat))) seq of
         BitSeq _ s b => W256 s b
   ) = (\<lambda> w .  word_of_int (integerFromBitSeq w)) seq)) "
(* Theorem: bs_to_w256_def_lemma*)(* try *) by auto

lemma w256_to_bs_def_lemma:
" ((\<forall> s. \<forall> b.
   BitSeq (Some (( 256 :: nat))) s b =
     (\<lambda> w .  bitSeqFromInteger (Some 256) ( (sint w))) (W256 s b))) "
(* Theorem: w256_to_bs_def_lemma*)(* try *) by auto

lemma word256ToNat_def_lemma:
" ((\<forall> w.
   nat
     (abs
        (
           (integerFromBitSeq
              ((\<lambda> w .  bitSeqFromInteger (Some 256) ( (sint w))) w))))
     = unat w)) "
(* Theorem: word256ToNat_def_lemma*)(* try *) by auto

lemma word256ToInt_def_lemma:
" ((\<forall> w.
   
     (integerFromBitSeq
        ((\<lambda> w .  bitSeqFromInteger (Some 256) ( (sint w))) w)) =
     sint w)) "
(* Theorem: word256ToInt_def_lemma*)(* try *) by auto

lemma word256FromInteger_def_lemma:
" ((\<forall> i.
   (\<lambda> w .  word_of_int (integerFromBitSeq w))
     (bitSeqFromInteger (Some (( 256 :: nat))) i) =
     (\<lambda> i .  word_of_int ( i)) i)) "
(* Theorem: word256FromInteger_def_lemma*)(* try *) by auto

lemma word256FromInt_def_lemma:
" ((\<forall> i.
   (\<lambda> w .  word_of_int (integerFromBitSeq w))
     (bitSeqFromInteger (Some (( 256 :: nat))) ( i)) = word_of_int i)) "
(* Theorem: word256FromInt_def_lemma*)(* try *) by auto

lemma word256FromBoollist_def_lemma:
" ((\<forall> lst.
   (case  bitSeqFromBoolList lst of
         None => (\<lambda> w .  word_of_int (integerFromBitSeq w))
                   (bitSeqFromInteger None (( 0 :: int)))
     | Some a => (\<lambda> w .  word_of_int (integerFromBitSeq w)) a
   ) = of_bl lst)) "
(* Theorem: word256FromBoollist_def_lemma*)(* try *) by auto

lemma boolListFromWord256_def_lemma:
" ((\<forall> w.
   boolListFrombitSeq (( 256 :: nat))
     ((\<lambda> w .  bitSeqFromInteger (Some 256) ( (sint w))) w) = 
   to_bl w)) "
(* Theorem: boolListFromWord256_def_lemma*)(* try *) by auto

lemma word256FromNumeral_def_lemma:
" ((\<forall> w.
   (\<lambda> w .  word_of_int (integerFromBitSeq w))
     (bitSeqFromInteger None (( w :: int))) = ((word_of_int w) :: 256 word))) "
(* Theorem: word256FromNumeral_def_lemma*)(* try *) by auto

lemma w256Less_def_lemma:
" ((\<forall> bs1. \<forall> bs2.
   word256BinTest bitSeqLess bs1 bs2 = word_sless bs1 bs2)) "
(* Theorem: w256Less_def_lemma*)(* try *) by auto

lemma w256LessEqual_def_lemma:
" ((\<forall> bs1. \<forall> bs2.
   word256BinTest bitSeqLessEqual bs1 bs2 = word_sle bs1 bs2)) "
(* Theorem: w256LessEqual_def_lemma*)(* try *) by auto

lemma w256Greater_def_lemma:
" ((\<forall> bs1. \<forall> bs2.
   word256BinTest bitSeqGreater bs1 bs2 = word_sless bs2 bs1)) "
(* Theorem: w256Greater_def_lemma*)(* try *) by auto

lemma w256GreaterEqual_def_lemma:
" ((\<forall> bs1. \<forall> bs2.
   word256BinTest bitSeqGreaterEqual bs1 bs2 = word_sle bs2 bs1)) "
(* Theorem: w256GreaterEqual_def_lemma*)(* try *) by auto

lemma w256Compare_def_lemma:
" ((\<forall> bs1. \<forall> bs2.
   word256BinTest bitSeqCompare bs1 bs2 =
     (genericCompare word_sless w256Eq bs1 bs2))) "
(* Theorem: w256Compare_def_lemma*)(* try *) by auto

lemma word256Negate_def_lemma:
" (( word256UnaryOp bitSeqNegate = (\<lambda> i. - i))) "
(* Theorem: word256Negate_def_lemma*)(* try *) by auto

lemma word256Succ_def_lemma:
" (( word256UnaryOp bitSeqSucc = (\<lambda> n. n + 1))) "
(* Theorem: word256Succ_def_lemma*)(* try *) by auto

lemma word256Pred_def_lemma:
" (( word256UnaryOp bitSeqPred = (\<lambda> n. n - 1))) "
(* Theorem: word256Pred_def_lemma*)(* try *) by auto

lemma word256Lnot_def_lemma:
" (( word256UnaryOp bitSeqNot = (\<lambda> w. (NOT w)))) "
(* Theorem: word256Lnot_def_lemma*)(* try *) by auto

lemma word256Add_def_lemma:
" (( word256BinOp bitSeqAdd = (op+))) "
(* Theorem: word256Add_def_lemma*)(* try *) by auto

lemma word256Minus_def_lemma:
" (( word256BinOp bitSeqMinus = (op-))) "
(* Theorem: word256Minus_def_lemma*)(* try *) by auto

lemma word256Mult_def_lemma:
" (( word256BinOp bitSeqMult = (op*))) "
(* Theorem: word256Mult_def_lemma*)(* try *) by auto

lemma word256IntegerDivision_def_lemma:
" (( word256BinOp bitSeqDiv = (op div))) "
(* Theorem: word256IntegerDivision_def_lemma*)(* try *) by auto

lemma word256Division_def_lemma:
" (( word256BinOp bitSeqDiv = (op div))) "
(* Theorem: word256Division_def_lemma*)(* try *) by auto

lemma word256Remainder_def_lemma:
" (( word256BinOp bitSeqMod = (op mod))) "
(* Theorem: word256Remainder_def_lemma*)(* try *) by auto

lemma word256Land_def_lemma:
" (( word256BinOp bitSeqAnd = (op AND))) "
(* Theorem: word256Land_def_lemma*)(* try *) by auto

lemma word256Lor_def_lemma:
" (( word256BinOp bitSeqOr = (op OR))) "
(* Theorem: word256Lor_def_lemma*)(* try *) by auto

lemma word256Lxor_def_lemma:
" (( word256BinOp bitSeqXor = (op XOR))) "
(* Theorem: word256Lxor_def_lemma*)(* try *) by auto

lemma word256Min_def_lemma:
" (( word256BinOp (bitSeqMin) = min)) "
(* Theorem: word256Min_def_lemma*)(* try *) by auto

lemma word256Max_def_lemma:
" (( word256BinOp (bitSeqMax) = max)) "
(* Theorem: word256Max_def_lemma*)(* try *) by auto

lemma word256Power_def_lemma:
" (( word256NatOp bitSeqPow = (op^))) "
(* Theorem: word256Power_def_lemma*)(* try *) by auto

lemma word256Asr_def_lemma:
" (( word256NatOp bitSeqArithmeticShiftRight = (op>>>))) "
(* Theorem: word256Asr_def_lemma*)(* try *) by auto

lemma word256Lsr_def_lemma:
" (( word256NatOp bitSeqLogicalShiftRight = (op>>))) "
(* Theorem: word256Lsr_def_lemma*)(* try *) by auto

lemma word256Lsl_def_lemma:
" (( word256NatOp bitSeqShiftLeft = (op<<))) "
(* Theorem: word256Lsl_def_lemma*)(* try *) by auto

lemma word256UGT_def_lemma:
" ((\<forall> a. \<forall> b. (unat a > unat b) = a > b)) "
(* Theorem: word256UGT_def_lemma*)(* try *) by auto



end
