chapter {* Generated by Lem from word8.lem. *}

theory "Word8Auxiliary" 

imports 
 	 Main "~~/src/HOL/Library/Code_Target_Numeral"
	 "Lem_pervasives" 
	 "Lem_word" 
	 "Word8" 

begin 


(****************************************************)
(*                                                  *)
(* Lemmata                                          *)
(*                                                  *)
(****************************************************)

lemma bs_to_w8_def_lemma:
" ((\<forall> seq.
   W8 (integerFromBitSeq seq) =
     (\<lambda> w .  word_of_int (integerFromBitSeq w)) seq)) "
(* Theorem: bs_to_w8_def_lemma*)(* try *) by auto

lemma w8_to_bs_def_lemma:
" ((\<forall> i.
   bitSeqFromInteger (Some (( 8 :: nat))) i =
     (\<lambda> w .  bitSeqFromInteger (Some 8) ( (sint w))) (W8 i))) "
(* Theorem: w8_to_bs_def_lemma*)(* try *) by auto

lemma word8ToNat_def_lemma:
" ((\<forall> w.
   nat
     (abs
        (
           (integerFromBitSeq
              ((\<lambda> w .  bitSeqFromInteger (Some 8) ( (sint w))) w))))
     = unat w)) "
(* Theorem: word8ToNat_def_lemma*)(* try *) by auto

lemma word8ToInt_def_lemma:
" ((\<forall> w.
   
     (integerFromBitSeq
        ((\<lambda> w .  bitSeqFromInteger (Some 8) ( (sint w))) w)) = 
   sint w)) "
(* Theorem: word8ToInt_def_lemma*)(* try *) by auto

lemma word8FromInteger_def_lemma:
" ((\<forall> i. W8 (i mod base) = (\<lambda> i .  word_of_int ( i)) i)) "
(* Theorem: word8FromInteger_def_lemma*)(* try *) by auto

lemma word8FromInt_def_lemma:
" ((\<forall> i. W8 ( i mod base) = word_of_int i)) "
(* Theorem: word8FromInt_def_lemma*)(* try *) by auto

lemma word8FromBoollist_def_lemma:
" ((\<forall> lst.
   (case  bitSeqFromBoolList lst of
         None => (\<lambda> w .  word_of_int (integerFromBitSeq w))
                   (bitSeqFromInteger None (( 0 :: int)))
     | Some a => (\<lambda> w .  word_of_int (integerFromBitSeq w)) a
   ) = of_bl lst)) "
(* Theorem: word8FromBoollist_def_lemma*)(* try *) by auto

lemma boolListFromWord8_def_lemma:
" ((\<forall> w.
   boolListFrombitSeq (( 8 :: nat))
     ((\<lambda> w .  bitSeqFromInteger (Some 8) ( (sint w))) w) = to_bl w)) "
(* Theorem: boolListFromWord8_def_lemma*)(* try *) by auto

lemma word8FromNumeral_def_lemma:
" ((\<forall> w. W8 (( w :: int) mod base) = ((word_of_int w) :: 8 word))) "
(* Theorem: word8FromNumeral_def_lemma*)(* try *) by auto

lemma w8Less_def_lemma:
" ((\<forall> bs1. \<forall> bs2.
   word8BinTest (op<) bs1 bs2 = word_sless bs1 bs2)) "
(* Theorem: w8Less_def_lemma*)(* try *) by auto

lemma w8LessEqual_def_lemma:
" ((\<forall> bs1. \<forall> bs2.
   word8BinTest (op \<le>) bs1 bs2 = word_sle bs1 bs2)) "
(* Theorem: w8LessEqual_def_lemma*)(* try *) by auto

lemma w8Greater_def_lemma:
" ((\<forall> bs1. \<forall> bs2.
   word8BinTest (op>) bs1 bs2 = word_sless bs2 bs1)) "
(* Theorem: w8Greater_def_lemma*)(* try *) by auto

lemma w8GreaterEqual_def_lemma:
" ((\<forall> bs1. \<forall> bs2.
   word8BinTest (op \<ge>) bs1 bs2 = word_sle bs2 bs1)) "
(* Theorem: w8GreaterEqual_def_lemma*)(* try *) by auto

lemma w8Compare_def_lemma:
" ((\<forall> bs1. \<forall> bs2.
   word8BinTest (genericCompare (op<) (op=)) bs1 bs2 =
     (genericCompare word_sless w8Eq bs1 bs2))) "
(* Theorem: w8Compare_def_lemma*)(* try *) by auto

lemma word8Negate_def_lemma:
" (( word8UnaryOp (\<lambda> i. - i) = (\<lambda> i. - i))) "
(* Theorem: word8Negate_def_lemma*)(* try *) by auto

lemma word8Succ_def_lemma:
" (( word8UnaryOp (\<lambda> n. n + ( 1 :: int)) = (\<lambda> n. n + 1))) "
(* Theorem: word8Succ_def_lemma*)(* try *) by auto

lemma word8Pred_def_lemma:
" (( word8UnaryOp (\<lambda> n. n - ( 1 :: int)) = (\<lambda> n. n - 1))) "
(* Theorem: word8Pred_def_lemma*)(* try *) by auto

lemma word8Lnot_def_lemma:
" (( word8UnaryOp integerLnot = (\<lambda> w. (NOT w)))) "
(* Theorem: word8Lnot_def_lemma*)(* try *) by auto

lemma word8Add_def_lemma:
" (( word8BinOp (op+) = (op+))) "
(* Theorem: word8Add_def_lemma*)(* try *) by auto

lemma word8Minus_def_lemma:
" (( word8BinOp (op-) = (op-))) "
(* Theorem: word8Minus_def_lemma*)(* try *) by auto

lemma word8Mult_def_lemma:
" (( word8BinOp (op*) = (op*))) "
(* Theorem: word8Mult_def_lemma*)(* try *) by auto

lemma word8IntegerDivision_def_lemma:
" (( word8BinOp (op div) = (op div))) "
(* Theorem: word8IntegerDivision_def_lemma*)(* try *) by auto

lemma word8Division_def_lemma:
" (( word8BinOp (op div) = (op div))) "
(* Theorem: word8Division_def_lemma*)(* try *) by auto

lemma word8Remainder_def_lemma:
" (( word8BinOp (op mod) = (op mod))) "
(* Theorem: word8Remainder_def_lemma*)(* try *) by auto

lemma word8Land_def_lemma:
" (( word8BinOp integerLand = (op AND))) "
(* Theorem: word8Land_def_lemma*)(* try *) by auto

lemma word8Lor_def_lemma:
" (( word8BinOp integerLor = (op OR))) "
(* Theorem: word8Lor_def_lemma*)(* try *) by auto

lemma word8Lxor_def_lemma:
" (( word8BinOp integerLxor = (op XOR))) "
(* Theorem: word8Lxor_def_lemma*)(* try *) by auto

lemma word8Min_def_lemma:
" (( word8BinOp (min) = min)) "
(* Theorem: word8Min_def_lemma*)(* try *) by auto

lemma word8Max_def_lemma:
" (( word8BinOp (max) = max)) "
(* Theorem: word8Max_def_lemma*)(* try *) by auto

lemma word8Power_def_lemma:
" (( word8NatOp (op^) = (op^))) "
(* Theorem: word8Power_def_lemma*)(* try *) by auto

lemma word8Asr_def_lemma:
" (( word8NatOp integerAsr = (op>>>))) "
(* Theorem: word8Asr_def_lemma*)(* try *) by auto

lemma word8Lsr_def_lemma:
" (( word8NatOp integerAsr = (op>>))) "
(* Theorem: word8Lsr_def_lemma*)(* try *) by auto

lemma word8Lsl_def_lemma:
" (( word8NatOp integerLsl = (op<<))) "
(* Theorem: word8Lsl_def_lemma*)(* try *) by auto

lemma word8UGT_def_lemma:
" ((\<forall> a. \<forall> b. (unat a > unat b) = a > b)) "
(* Theorem: word8UGT_def_lemma*)(* try *) by auto



end
